In [1]:
import pandas as pd

In [2]:
cd /Users/shrabanighosh/UNCC/Spring 2025/plos complex/csvfiles/

/Users/shrabanighosh/UNCC/Spring 2025/plos complex/csvfiles

/Users/shrabanighosh/thematic/lib/python3.9/site-packages/IPython/core/magics/osm.py:417: UserWarning: using dhist requires you to install the `pickleshare` library.
  self.shell.db['dhist'] = compress_dhist(dhist)[-100:]

In [8]:
ls

confs_with_orcid.csv  groupby_orcid.csv     unique_orcids.csv
dblp.csv              orcid_name_id.csv

In [4]:
df = pd.read_csv('orcid_name_id.csv')
df

,Unnamed: 0,orcid,authors_name,booktitle
0,0,0000-0001-9128-0391,Jonathan Immanuel Brachthuser,Denert Award
1,1,0000-0002-6667-5452,Florian Matthes,Denert Award
2,2,0000-0002-0529-7267,Sven Reichel,IWSDS
3,3,0000-0003-2460-9673,Jason D. Williams,IWSDS
4,4,0000-0001-8650-5154,Hyung-Bae Jeon,IWSDS
...,...,...,...,...
2130381,2130381,0000-0001-8285-5624,Oscar Vilarroya,PT-AI
2130382,2130382,0000-0002-4414-6920,Claiborne Rice,PT-AI
2130383,2130383,0000-0002-4182-3228,Sam Freed,PT-AI
2130384,2130384,0000-0002-2126-0843,Claudius Gros,PT-AI
2130385,2130385,0000-0003-2351-930X,Lambert Schomaker,PT-AI

In [12]:
new_df = df.groupby('booktitle')['orcid'].apply(list)

In [15]:
new_df = new_df.reset_index()

In [22]:
new_df['len'] = new_df['orcid'].apply(len)
new_df = new_df.sort_values(by = 'len',ascending=False)
new_df

,booktitle,orcid,11247,len
3197,EMBC,"[0009-0000-1191-7226, 0000-0002-1773-0064, 000...",26518,26518
5714,IGARSS,"[0000-0002-6543-119X, 0000-0002-9209-0685, 000...",21106,21106
1574,CHI,"[0000-0001-7477-6782, 0000-0001-8041-2520, 000...",18343,18343
4728,ICASSP,"[0000-0002-1967-2718, 0000-0001-6937-7218, 000...",17719,17719
247,ACM Multimedia,"[0000-0002-5549-9027, 0000-0002-5372-0656, 000...",16401,16401
...,...,...,...,...
8624,RACES@SPLASH,[0000-0003-0014-6483],1,1
10328,TwinTalks@DH/DHN,[0000-0002-3887-5342],1,1
10334,UAI Application Workshops,[0000-0002-8876-9337],1,1
3273,ER Forum/Demos,[0000-0001-7198-8552],1,1
6294,ITPM,[0000-0002-0001-0140],1,1

In [24]:
def unique_list(lst):
    return list(set(lst))

In [30]:
new_df['orcid_unique'] = new_df['orcid'].apply(unique_list)
new_df['unique_len'] = new_df['orcid_unique'].apply(len)
new_df = new_df.sort_values(by = 'unique_len',ascending=False)
new_df

,booktitle,orcid,11247,len,orcid_unique,unique_len
3197,EMBC,"[0009-0000-1191-7226, 0000-0002-1773-0064, 000...",26518,26518,"[0000-0002-1138-5036, 0000-0001-7610-850X, 000...",11420
247,ACM Multimedia,"[0000-0002-5549-9027, 0000-0002-5372-0656, 000...",16401,16401,"[0009-0008-1882-3124, 0009-0004-0938-3690, 000...",10274
1574,CHI,"[0000-0001-7477-6782, 0000-0001-8041-2520, 000...",18343,18343,"[0009-0003-6434-083X, 0000-0002-5121-6296, 000...",8909
1651,CIKM,"[0000-0003-2368-7506, 0000-0002-6591-0879, 000...",11123,11123,"[0000-0002-6247-7504, 0000-0002-5204-4895, 000...",6985
1578,CHI Extended Abstracts,"[0009-0006-0544-5182, 0009-0003-1383-8160, 000...",12889,12889,"[0009-0001-7116-266X, 0000-0002-5121-6296, 000...",6953
...,...,...,...,...,...,...
2349,Conference on Computer Logic,[0000-0002-3739-9161],1,1,[0000-0002-3739-9161],1
5586,ICYCSEE,[0000-0002-2872-388X],1,1,[0000-0002-2872-388X],1
2303,Complexity of Computer Computations,[0000-0002-8495-7437],1,1,[0000-0002-8495-7437],1
7733,NATO Neurocomputing,[0000-0002-5032-4228],1,1,[0000-0002-5032-4228],1
6294,ITPM,[0000-0002-0001-0140],1,1,[0000-0002-0001-0140],1

In [59]:
new_df.to_csv('groupby_orcid.csv')

In [28]:
new_df.head(30)

,booktitle,orcid,11247,len,orcid_unique,unique_len
3197,EMBC,"[0009-0000-1191-7226, 0000-0002-1773-0064, 000...",26518,26518,"[0000-0002-1138-5036, 0000-0001-7610-850X, 000...",11420
5714,IGARSS,"[0000-0002-6543-119X, 0000-0002-9209-0685, 000...",21106,21106,"[0000-0003-4229-7482, 0000-0002-4146-1941, 000...",6273
1574,CHI,"[0000-0001-7477-6782, 0000-0001-8041-2520, 000...",18343,18343,"[0009-0003-6434-083X, 0000-0002-5121-6296, 000...",8909
4728,ICASSP,"[0000-0002-1967-2718, 0000-0001-6937-7218, 000...",17719,17719,"[0000-0001-8362-5927, 0000-0002-5997-282X, 000...",6500
247,ACM Multimedia,"[0000-0002-5549-9027, 0000-0002-5372-0656, 000...",16401,16401,"[0009-0008-1882-3124, 0009-0004-0938-3690, 000...",10274
1499,CDC,"[0000-0002-9982-5488, 0000-0003-2633-9929, 000...",15441,15441,"[0000-0003-3554-8933, 0000-0002-0808-0274, 000...",4460
5400,ICRA,"[0000-0002-5739-1618, 0000-0002-9199-7373, 000...",14796,14796,"[0000-0002-1163-037X, 0000-0002-5575-8244, 000...",5304
4772,ICC,"[0000-0002-9960-7800, 0000-0001-8810-0345, 000...",14572,14572,"[0000-0001-6945-3196, 0000-0003-0950-1111, 000...",5096
5973,IROS,"[0000-0002-2593-2141, 0000-0002-4932-9777, 000...",13890,13890,"[0000-0003-1493-7147, 0000-0002-5848-8892, 000...",5320
1578,CHI Extended Abstracts,"[0009-0006-0544-5182, 0009-0003-1383-8160, 000...",12889,12889,"[0009-0001-7116-266X, 0000-0002-5121-6296, 000...",6953
4080,GLOBECOM,"[0000-0003-4893-6847, 0000-0003-2968-2060, 000...",12656,12656,"[0000-0001-7351-0341, 0000-0003-0868-143X, 000...",4542
5629,IECON,"[0000-0002-0736-5040, 0000-0002-7438-8904, 000...",11623,11623,"[0000-0002-7591-2720, 0009-0000-0785-8884, 000...",4925
1651,CIKM,"[0000-0003-2368-7506, 0000-0002-6591-0879, 000...",11123,11123,"[0000-0002-6247-7504, 0000-0002-5204-4895, 000...",6985
5146,ICIP,"[0000-0002-1140-6685, 0000-0002-7567-7177, 000...",10412,10412,"[0000-0001-8915-3043, 0000-0001-8994-1736, 000...",4437
147,ACC,"[0000-0002-8592-7934, 0000-0002-8592-7934, 000...",10289,10289,"[0000-0003-2862-4512, 0000-0002-7940-511X, 000...",3682
6035,ISCAS,"[0000-0002-3166-5529, 0000-0002-5509-5065, 000...",9864,9864,"[0000-0002-8141-2511, 0000-0002-7828-0239, 000...",4057
5791,IJCNN,"[0000-0002-5788-0446, 0000-0002-6172-020X, 000...",9631,9631,"[0000-0002-0626-5048, 0000-0002-6210-0678, 000...",4902
6676,KDD,"[0009-0002-4611-628X, 0009-0001-6334-245X, 000...",9443,9443,"[0000-0003-0591-2845, 0000-0002-1454-4514, 000...",6104
2146,CVPR,"[0000-0002-1015-4770, 0000-0003-2439-350X, 000...",8817,8817,"[0000-0002-8153-341X, 0000-0002-8868-8094, 000...",3198
9450,SMC,"[0000-0002-5269-0125, 0000-0003-1933-7343, 000...",8193,8193,"[0000-0002-7233-6916, 0000-0002-8131-4938, 000...",4386
6019,ISBI,"[0000-0002-9416-1803, 0000-0003-0571-6983, 000...",7707,7707,"[0000-0001-6403-2827, 0000-0002-5212-3294, 000...",3375
8908,SAC,"[0000-0001-8992-4768, 0000-0003-3275-3333, 000...",7667,7667,"[0000-0001-5660-2447, 0000-0003-3460-8674, 000...",5053
9344,SIGIR,"[0000-0002-9447-4172, 0000-0002-4046-3419, 000...",7402,7402,"[0000-0001-5653-3349, 0000-0002-9054-9747, 000...",4072
11006,WWW,"[0000-0002-1931-585X, 0000-0003-1913-6808, 000...",6730,6730,"[0000-0002-1358-4215, 0009-0003-0803-2656, 000...",4626
8253,PIMRC,"[0000-0002-6798-7001, 0000-0001-6201-4270, 000...",6318,6318,"[0000-0003-2322-8609, 0000-0003-0868-143X, 000...",2857
10732,WCNC,"[0000-0001-5856-523X, 0000-0002-9575-1063, 000...",6095,6095,"[0000-0003-2322-8609, 0000-0001-6406-0932, 000...",2793
3891,FUZZ-IEEE,"[0000-0003-3076-4688, 0000-0002-1466-2887, 000...",5833,5833,"[0000-0002-9849-9297, 0000-0003-3673-421X, 000...",2290
6114,ISIT,"[0000-0003-4966-3684, 0000-0002-3162-8058, 000...",5732,5732,"[0000-0001-6406-0932, 0000-0002-2265-4887, 000...",1502
10593,VTC Spring,"[0000-0001-6727-5867, 0000-0001-9236-2655, 000...",5402,5402,"[0000-0003-4036-1364, 0000-0003-3429-7212, 000...",2539
6302,ITSC,"[0000-0002-9938-0255, 0000-0002-1019-9004, 000...",5344,5344,"[0000-0003-4123-1385, 0000-0002-1543-195X, 000...",2654

In [58]:
new_df[['booktitle','unique_len']].to_csv('usable.csv')

In [52]:
new_df.columns

Index(['booktitle', 'orcid', 11247, 'len', 'orcid_unique', 'unique_len'], dtype='object')

In [53]:
new_df = new_df.reset_index()
new_df = new_df[['booktitle', 'orcid','len', 'orcid_unique', 'unique_len']]
new_df

,booktitle,orcid,len,orcid_unique,unique_len
0,EMBC,"[0009-0000-1191-7226, 0000-0002-1773-0064, 000...",26518,"[0000-0002-1138-5036, 0000-0001-7610-850X, 000...",11420
1,ACM Multimedia,"[0000-0002-5549-9027, 0000-0002-5372-0656, 000...",16401,"[0009-0008-1882-3124, 0009-0004-0938-3690, 000...",10274
2,CHI,"[0000-0001-7477-6782, 0000-0001-8041-2520, 000...",18343,"[0009-0003-6434-083X, 0000-0002-5121-6296, 000...",8909
3,CIKM,"[0000-0003-2368-7506, 0000-0002-6591-0879, 000...",11123,"[0000-0002-6247-7504, 0000-0002-5204-4895, 000...",6985
4,CHI Extended Abstracts,"[0009-0006-0544-5182, 0009-0003-1383-8160, 000...",12889,"[0009-0001-7116-266X, 0000-0002-5121-6296, 000...",6953
...,...,...,...,...,...
11242,Conference on Computer Logic,[0000-0002-3739-9161],1,[0000-0002-3739-9161],1
11243,ICYCSEE,[0000-0002-2872-388X],1,[0000-0002-2872-388X],1
11244,Complexity of Computer Computations,[0000-0002-8495-7437],1,[0000-0002-8495-7437],1
11245,NATO Neurocomputing,[0000-0002-5032-4228],1,[0000-0002-5032-4228],1
11246,ITPM,[0000-0002-0001-0140],1,[0000-0002-0001-0140],1

In [54]:
# dmlist = ['CIKM','KDD','SIGIR','WWW','WSDM','IEEE BigData', 'ICDM', 'ASONAM', 'RecSys', 'ICDM Workshops', 'ICDE', 'ICMLA']
dmlist = ['CIKM','KDD','SIGIR','WWW','WSDM','IEEE BigData']
new_df[new_df['booktitle'].isin(dmlist)]
new_df[new_df['booktitle'].isin(dmlist)]['unique_len'].sum()
# new_df[new_df['booktitle'].isin(dmlist)].to_csv('dm.csv')

25783

In [55]:
swlist = ['ICSE','ASE', 'ESEC/SIGSOFT FSE' ,'COMPSAC' , 'ISSTA' , 'UIST' ]
new_df[new_df['booktitle'].isin(swlist)]
new_df[new_df['booktitle'].isin(swlist)]['unique_len'].sum()
# new_df[new_df['booktitle'].isin(dmlist)].to_csv('dm.csv')

8248

In [56]:
hrilist=['HRI','HRI (Companion)','ROBIO' , 'IROS' , 'ICRA']
new_df[new_df['booktitle'].isin(hrilist)]
new_df[new_df['booktitle'].isin(hrilist)]['unique_len'].sum()

15178

In [57]:
cvlist = ['CVPR', 'CVPR Workshops' , 'ICCV' , 'ICPR' , 'WACV' ]
new_df[new_df['booktitle'].isin(cvlist)]
# new_df[new_df['booktitle'].isin(cvlist)]['unique_len'].sum()

,booktitle,orcid,len,orcid_unique,unique_len
25,CVPR,"[0000-0002-1015-4770, 0000-0003-2439-350X, 000...",8817,"[0000-0002-8153-341X, 0000-0002-8868-8094, 000...",3198
30,ICPR,"[0000-0002-1478-0402, 0000-0001-5169-4047, 000...",4378,"[0000-0002-4704-0718, 0000-0002-8420-3520, 000...",2614
51,ICCV,"[0000-0002-4093-7557, 0000-0002-3802-4644, 000...",4008,"[0000-0002-5176-9202, 0000-0002-2223-2887, 000...",1986
58,CVPR Workshops,"[0000-0001-7650-0579, 0000-0001-6611-5327, 000...",3150,"[0000-0002-1946-4150, 0000-0003-3673-421X, 000...",1904
118,WACV,"[0000-0002-6601-7302, 0000-0002-6822-2801, 000...",2082,"[0000-0002-0603-3669, 0000-0003-0867-7908, 000...",1288